config/routes.rb
Rails.application.routes.draw do
	root 'sessions#new'
	get '/select', to: 'sessions#new'
	post '/select', to: 'sessions#create'
	
	resources :statements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/helicopter.rb
class Helicopter < ApplicationRecord
	has_many :statements
end

app/models/statement.rb
class Statement < ApplicationRecord
	belongs_to :helicopter
	has_many :tasks, inverse_of: :statement
	accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
	validates :crs, presence: true, length: {minimum: 12}
	validates :sot, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :statement
  validates :title, :term, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  	@statements = Statement.all
  end

  def create
	session[:selected_helicopter_id] = params[:helicopter][:id]
	if session[:selected_helicopter_id].empty?
		flash[:danger] = 'Select a helicopter'
		redirect_to select_path
	else
		redirect_to new_statement_path
	end
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
	before_action :find_statement, only: [:show, :edit, :update, :destroy]

	def show
		respond_to do |format|
			format.html
			format.pdf do
				render pdf: "MaintenanceStatement",
				template: "statements/show.pdf.haml",
				locals: {:statement => @statement},
				encoding: "UTF-8"
			end
		end
	end

	def new
		@current_helicopter = Helicopter.find_by(id: session[:selected_helicopter_id])
		@statement = @current_helicopter.statements.build
	end

	def create
		@current_helicopter = Helicopter.find_by(id: session[:selected_helicopter_id])
		@statement = @current_helicopter.statements.build(statement_params)
		if @statement.save
			flash[:success] = 'MS almost done'
			redirect_to @statement
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @statement.update(statement_params)
			redirect_to @statement
		else
			render 'edit'
		end
	end

	def destroy
		@statement.destroy
		redirect_to select_path
	end

	private

	def statement_params
		params.require(:statement).permit(:sot, :crs, tasks_attributes: [:id, :title, :term, :_destroy])
	end

	def find_statement
		@statement = Statement.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
	.container
		= link_to 'Brand', root_path, class: 'navbar-brand'
		%ul.nav.navbar-nav
			%li.active= link_to 'Link', '#'
			%li= link_to 'Link', '#'
		%ul.nav.navbar-nav.navbar-right
			%li= link_to 'Sign in', '#'

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title MsMaster
		= csrf_meta_tags
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		= render 'layouts/header'
		.container
			- flash.each do |msg_type, msg|
				= content_tag(:div, msg, class: "alert alert-#{msg_type}")
			= yield

app/views/statements/_form.html.haml
= form_for(@statement) do |f|
	- if @statement.errors.any?
		%ul.alert.alert-warning
			%b= pluralize(@statement.errors.count, "error")
			- @statement.errors.full_messages.each do |msg|
				%li= msg
	.form-group
		= f.label :crs
		= f.text_field :crs, class: 'form-control'
	.form-group
		= f.label :sot
		= f.text_field :sot, class: 'form-control'
	.form-group
		%label Tasks
		#tasks
			= f.fields_for :tasks do |task|
				= render 'task_fields', f: task
			.links
				= link_to_add_association f, :tasks, class: 'btn btn-success' do
					%span.glyphicon.glyphicon-plus
					Add task
	%hr
	= link_to 'Back', select_path, class: 'btn btn-default'
	= f.submit class: 'btn btn-primary'

app/views/statements/_printout.html.haml
.container
	.row.row-eq-height
		.col-xs-4.img-centered
			= image_tag("logo_super.jpg", alt: "Logo", width: "103", height: "100")
		.col-xs-4
			LOTNICZE POGOTOWIE RATUNKOWE
		.col-xs-4
			ul. Księżycowa 5
			%br
			01-934 Warszawa
			%br
			Certyfikat Part M Podczesc G PL.MG.005
	.row.row-eq-height
		.col-xs-12
			%h4
				%b ŚWIADECTWO OBSŁUGI TECHNICZNEJ
				%br
				(MAINTENANCE STATEMENT)
			%h3
				MS Nr:
				%b MS-#{ @statement.helicopter.registration[-3, 3] }-#{ @statement.helicopter.last_ms.to_s.rjust(3, '0') }
	.row.row-eq-height
		.col-xs-4
			%b Typ statku powietrznego:
			
			(Aircraft type):
		.col-xs-8
			EC 135 P3
	.row.row-eq-height
		.col-xs-4
			%b Znaki rozpoznawcze:
			%br
			(Tail number)
		.col-xs-8
			SP-DXD
	.row.row-eq-height
		.col-xs-4
			%b Numer fabryczny:
			%br
			(Serial number)
		.col-xs-8
			1209
	.row
		.col-xs-12
			%p.small
				%b Oświadczenie (Statement):
				%br
				Oświadczam, że planowa hangarowa obsługa techniczna statku powietrznego o danych wymienionych powyżej, wykonana według:
				%br
				%i
					Programu Obsługi Technicznej nr 
					%b PROBT- EC135
					zmiana nr.
					%b 18 ZP
				%br
				jest ważna do czasu osiągnięcia parametrów określających jego eksploatację, podanych w Ograniczeniach Zdatności	do Lotu.
				%br
			%p.small
				I declare, that the base maintenance of aircraft identified above, done according to:
				%br
				%i
					Maintenance Programme n°
					%b PROBT- EC135
					revision no.
					%b 18 ZP
				%br
				is valid until reaching parameters defining exploatation, given in the Due Task Limitations.
	.row.row-eq-height
		.col-xs-4
			%b Nr CRS
			%br
			(CRS Number)
		.col-xs-4
			%b Organizacja wykonująca
			%br
			(Maintenance Organization)
		.col-xs-4
			%b Nr certyfikatu organizacji
			%br
			(Organization Number)
	.row.row-eq-height
		.col-xs-4
			%b 001/001/DXA/01
		.col-xs-4
			%b SOT Szczecin
		.col-xs-4
			%b PL.145.022
	.row.row-eq-height
		.col-xs-6.img-centered
			= image_tag("signature.png", alt: "Engineer", width: "200", height: "90")
			%p (Nazwisko i podpis oświadczającego)
		.col-xs-6.img-centered
			= image_tag("signature.png", alt: "CompanyStamp", width: "200", height: "90")
			%p (Pieczęć firmowa - Company stamp)
/DRUGA STRONA
.container
	.row.row-eq-height
		.col-xs-2.img-centered
			= image_tag("logo_super.jpg", alt: "Logo-small", width: "65", height: "62")
		.col-xs-10
			OGRANICZENIA ZDATNOŚCI SP DO LOTU MS Nr:
			%b MS-DXA-003
			%br
			(DUE TASK LIMITATION - MS N°)
	.row
		.col-xs-12
			%b Statek Powietrzny zachowuje zdatność do lotu pod warunkiem usunięcia podanych niżej ograniczeń przez wykonanie podanych czynności obsługowych:
			%br
			(The aircraft will keep airworthiness on condition of removing below given limitations by complying with the written maintenance tasks)
	.row.row-eq-height
		.col-xs-1
			%b Lp
			%br
			Item
		.col-xs-3
			%b Czynności obsługowe
			%br
			(Maintenance task)
		.col-xs-2
			%b Termin wykonania
			%br
			(Term to comply with)
		.col-xs-6
			%b Potwierdzenie wykonania obsługi
			%br
			(Confirmation of done maintenance)
			.row.row-eq-height
				.col-xs-4
					%b Nr CRS
					%br
					(CRS no.)
				.col-xs-4
					%b Data
					%br
					(Date)
				.col-xs-4
					%b Podpis CAMO
					%br
					(Signature)
	.row.row-eq-height
		.col-xs-1
			1.
		.col-xs-3
		.col-xs-2
		.col-xs-2
		.col-xs-2
		.col-xs-2
	.row.row-eq-height
		.col-xs-1
			2.
		.col-xs-3
		.col-xs-2
		.col-xs-2
		.col-xs-2
		.col-xs-2

app/views/statements/_statement.html.haml
%p
	MS-#{ statement.helicopter.registration[-3, 3] }-#{ statement.helicopter.last_ms.to_s.rjust(3, '0') } 
	| #{ statement.created_at } | Created by Elon
	|
	= link_to 'Edit', statement

app/views/statements/_task_fields.html.haml
.nested-fields
	.form-horizontal
		.form-group
			.col-sm-8
				= f.text_field :title, placeholder: 'Task Title', class: 'form-control'
			.col-sm-3
				= f.text_field :term, placeholder: 'Deadline', class: 'form-control'
			.col-sm-1
				= link_to_remove_association f, class: 'btn btn-danger' do
					%span.glyphicon.glyphicon-minus

app/views/statements/edit.html.haml
%h1 Edit MS
= render "statements/form"

app/views/statements/new.html.haml
%h2 MS-#{ @current_helicopter.registration[-3, 3] }-#{ @current_helicopter.last_ms.to_s.rjust(3, '0') }
%h5
	= @current_helicopter.registration
	= @current_helicopter.serial_number	
%hr
= render 'statements/form'

app/views/statements/show.html.haml
%h3= @statement.helicopter.registration
%h5 MS-#{ @statement.helicopter.registration[-3, 3] }-#{ @statement.helicopter.last_ms.to_s.rjust(3, '0') } | Created by Elon
%hr
%h5 Tasks
%ul
	- @statement.tasks.each do |task|
		%li
			= task.title
			= task.term
%hr
= link_to 'Back', select_path, class: 'btn btn-default'
= link_to 'Edit', edit_statement_path, class: 'btn btn-default'
= link_to 'Delete', statement_path, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?'}
= link_to 'Create PDF', statement_path(@statement, :format => :pdf), class: 'btn btn-default'

/= render 'printout'
%br

app/views/statements/show.pdf.haml
!!! 5
%html
	%head
		%title MsMaster
		= wicked_pdf_stylesheet_link_tag "application"
	%body
		.container
			.row.row-eq-height
				.col-xs-4.img-centered
					= wicked_pdf_image_tag("logo_super.jpg", alt: "Logo", width: "103", height: "100")
				.col-xs-4
					LOTNICZE POGOTOWIE RATUNKOWE
				.col-xs-4
					ul. Księżycowa 5
					%br
					01-934 Warszawa
					%br
					Certyfikat Part M Podczesc G PL.MG.005
			.row.row-eq-height
				.col-xs-12
					%h4
						%b ŚWIADECTWO OBSŁUGI TECHNICZNEJ
						%br
						(MAINTENANCE STATEMENT)
					%h3
						MS Nr:
						%b MS-#{ @statement.helicopter.registration[-3, 3] }-#{ @statement.helicopter.last_ms.to_s.rjust(3, '0') }
			.row.row-eq-height
				.col-xs-4
					%b Typ statku powietrznego:
					
					(Aircraft type):
				.col-xs-8
					EC 135 P3
			.row.row-eq-height
				.col-xs-4
					%b Znaki rozpoznawcze:
					%br
					(Tail number)
				.col-xs-8
					SP-DXD
			.row.row-eq-height
				.col-xs-4
					%b Numer fabryczny:
					%br
					(Serial number)
				.col-xs-8
					1209
			.row
				.col-xs-12
					%p.small
						%b Oświadczenie (Statement):
						%br
						Oświadczam, że planowa hangarowa obsługa techniczna statku powietrznego o danych wymienionych powyżej, wykonana według:
						%br
						%i
							Programu Obsługi Technicznej nr 
							%b PROBT- EC135
							zmiana nr.
							%b 18 ZP
						%br
						jest ważna do czasu osiągnięcia parametrów określających jego eksploatację, podanych w Ograniczeniach Zdatności	do Lotu.
						%br
					%p.small
						I declare, that the base maintenance of aircraft identified above, done according to:
						%br
						%i
							Maintenance Programme n°
							%b PROBT- EC135
							revision no.
							%b 18 ZP
						%br
						is valid until reaching parameters defining exploatation, given in the Due Task Limitations.
			.row.row-eq-height
				.col-xs-4
					%b Nr CRS
					%br
					(CRS Number)
				.col-xs-4
					%b Organizacja wykonująca
					%br
					(Maintenance Organization)
				.col-xs-4
					%b Nr certyfikatu organizacji
					%br
					(Organization Number)
			.row.row-eq-height
				.col-xs-4
					%b 001/001/DXA/01
				.col-xs-4
					%b SOT Szczecin
				.col-xs-4
					%b PL.145.022
			.row.row-eq-height
				.col-xs-6.img-centered
					= image_tag("signature.png", alt: "Engineer", width: "200", height: "90")
					%p (Nazwisko i podpis oświadczającego)
				.col-xs-6.img-centered
					= image_tag("signature.png", alt: "CompanyStamp", width: "200", height: "90")
					%p (Pieczęć firmowa - Company stamp)
		/DRUGA STRONA
		.container
			.row.row-eq-height
				.col-xs-2.img-centered
					= image_tag("logo_super.jpg", alt: "Logo-small", width: "65", height: "62")
				.col-xs-10
					OGRANICZENIA ZDATNOŚCI SP DO LOTU MS Nr:
					%b MS-DXA-003
					%br
					(DUE TASK LIMITATION - MS N°)
			.row
				.col-xs-12
					%b Statek Powietrzny zachowuje zdatność do lotu pod warunkiem usunięcia podanych niżej ograniczeń przez wykonanie podanych czynności obsługowych:
					%br
					(The aircraft will keep airworthiness on condition of removing below given limitations by complying with the written maintenance tasks)
			.row.row-eq-height
				.col-xs-1
					%b Lp
					%br
					Item
				.col-xs-3
					%b Czynności obsługowe
					%br
					(Maintenance task)
				.col-xs-2
					%b Termin wykonania
					%br
					(Term to comply with)
				.col-xs-6
					%b Potwierdzenie wykonania obsługi
					%br
					(Confirmation of done maintenance)
					.row.row-eq-height
						.col-xs-4
							%b Nr CRS
							%br
							(CRS no.)
						.col-xs-4
							%b Data
							%br
							(Date)
						.col-xs-4
							%b Podpis CAMO
							%br
							(Signature)
			.row.row-eq-height
				.col-xs-1
					1.
				.col-xs-3
				.col-xs-2
				.col-xs-2
				.col-xs-2
				.col-xs-2
			.row.row-eq-height
				.col-xs-1
					2.
				.col-xs-3
				.col-xs-2
				.col-xs-2
				.col-xs-2
				.col-xs-2